name: Build, Test, Pack and Push to Nuget feed

on:
  workflow_call:
    inputs:
      projects:
        required: true
        type: string
    secrets:
      nuser:
        required: true
      npass:
        required: true
      NUGET_KEY:
        required: true
      NUGET_SOURCE:
        required: true
      NUGET_SYM_SOURCE:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - uses: actions/setup-dotnet@v1
        name: Setup .NET
        with:
          dotnet-version: 6.0.x
      - uses: boegholm/PreparePrivateNugetFeed@master
        with:
          nuser: ${{ secrets.nuser }}
          npass: ${{ secrets.npass }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_SYM_SOURCE: ${{ secrets.NUGET_SYM_SOURCE }}

      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - uses: boegholm/PushProjectToNugetFeed@master
        with:
          projects: ${{ inputs.projects }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_SYM_SOURCE: ${{ secrets.NUGET_SYM_SOURCE }}
